export const BUILDING_LIST = [
  {
    raceId: 2,
    building_id: 1,
    energy: 3,
    openUnitIds: [1, 2],
    openBuildingIds: [2],
    name: '教学楼',
    weight: 1,
    img: 'magic_building_1',
  },
  {
    raceId: 2,
    building_id: 2,
    energy: 6,
    openUnitIds: [],
    openBuildingIds: [3, 4, 5],
    name: '图书馆',
    weight: 2,
    img: 'magic_building_2',
  },
  {
    raceId: 2,
    building_id: 3,
    energy: 4,
    openUnitIds: [3],
    openBuildingIds: [],
    name: '藏经阁',
    weight: 3,
    img: 'magic_building_3',
  },
  {
    raceId: 2,
    building_id: 4,
    energy: 4,
    openUnitIds: [4],
    openBuildingIds: [],
    name: '密室',
    weight: 3,
    img: 'magic_building_4',
  },
  {
    raceId: 2,
    building_id: 5,
    energy: 6,
    openUnitIds: [],
    openBuildingIds: [6, 7],
    name: '城堡',
    weight: 4,
    img: 'magic_building_5',
  },
  {
    raceId: 2,
    building_id: 6,
    energy: 4,
    openUnitIds: [5, 6],
    openBuildingIds: [8],
    name: '魔导殿堂',
    weight: 5,
    img: 'magic_building_6',
  },
  {
    raceId: 2,
    building_id: 7,
    energy: 4,
    openUnitIds: [7],
    openBuildingIds: [],
    name: '符文地窖',
    weight: 5,
    img: 'magic_building_7',
  },
  {
    raceId: 2,
    building_id: 8,
    energy: 4,
    openUnitIds: [8],
    openBuildingIds: [9],
    name: '法师塔',
    weight: 6,
    img: 'magic_building_8',
  },
  {
    raceId: 2,
    building_id: 9,
    energy: 4,
    openUnitIds: [9],
    openBuildingIds: [10],
    name: '宝库',
    weight: 7,
    img: 'magic_building_9',
  },
  {
    raceId: 2,
    building_id: 10,
    energy: 5,
    openUnitIds: [10, 11],
    openBuildingIds: [],
    name: '神迹',
    weight: 8,
    img: 'magic_building_10',
  },
]