export const UNIT_LIST = [
  {
    raceId: 2,
    unit_id: 1,
    atk: 1,
    hp: 1,
    af: 1,
    energy: 1,
    weight: 1,
    name: '学童',
    effect: 'onClick',
    effect_des: '对方随机单位HP-1',
    effectFunc: 'magicChild',
    img: 'magic_unit_1',
  },
  {
    raceId: 2,
    unit_id: 2,
    atk: 1,
    hp: 1,
    af: 1,
    energy: 2,
    weight: 1,
    name: '导师',
    effect: 'onClick',
    effect_des: '我方随机单位攻击力+1',
    effectFunc: 'magicTeacher',
    img: 'magic_unit_2',
  },
  {
    raceId: 2,
    unit_id: 3,
    atk: 1,
    hp: 6,
    af: 1,
    energy: 3,
    weight: 1,
    name: '先知',
    effect: 'onClick',
    effect_des: '对方随机单位生命值-3并效果无效化',
    effectFunc: 'prophet',
    img: 'magic_unit_3',
  },
  {
    raceId: 2,
    unit_id: 4,
    atk: 3,
    hp: 4,
    af: 2,
    energy: 3,
    weight: 1,
    name: '堕落使徒',
    effect: 'onShow',
    effect_des: '不会受到对方攻击破坏',
    effectFunc: 'apostle',
    img: 'magic_unit_4',
  },
  {
    raceId: 2,
    unit_id: 5,
    atk: 2,
    hp: 8,
    af: 3,
    energy: 4,
    weight: 4,
    name: '魔导师',
    effect: 'onShow',
    effect_des: '攻击对方单位且双方并没破坏后，对方单位变成一只1/1/1的青蛙',
    effectFunc: 'magicGuide',
    img: 'magic_unit_5',
  },
  {
    raceId: 2,
    unit_id: 6,
    atk: 5,
    hp: 5,
    af: 1,
    energy: 3,
    weight: 4,
    name: '传教士',
    effect: 'onShow',
    effect_des: '消灭对方单位后，对方该单位左右各一个单位hp-5',
    effectFunc: 'missionary',
    img: 'magic_unit_6',
  },
  {
    raceId: 2,
    unit_id: 7,
    atk: 3,
    hp: 6,
    af: 1,
    energy: 2,
    weight: 4,
    name: '咒术师',
    effect: 'onShow',
    effect_des: '对方开始回合随机单位进入沉睡',
    effectFunc: 'charm',
    img: 'magic_unit_7',
  },
  {
    raceId: 2,
    unit_id: 8,
    atk: 4,
    hp: 7,
    af: 1,
    energy: 4,
    weight: 5,
    name: '法王',
    effect: 'onShow',
    effect_des: '我方单位发动效果后，对方所有单位hp-1',
    effectFunc: 'pharaoh',
    img: 'magic_unit_8',
  },
  {
    raceId: 2,
    unit_id: 9,
    atk: 3,
    hp: 9,
    af: 1,
    energy: 4,
    weight: 4,
    name: '牧师',
    effect: 'onClick',
    effect_des: '我方指挥官hp+4',
    effectFunc: 'priest',
    img: 'magic_unit_9',
  },
  {
    raceId: 2,
    unit_id: 10,
    atk: 5,
    hp: 6,
    af: 1,
    energy: 3,
    weight: 4,
    name: '结界师',
    effect: 'onShow',
    effect_des: '我方单位攻击不会被破坏',
    effectFunc: 'boundary',
    img: 'magic_unit_10',
  },
  {
    raceId: 2,
    unit_id: 11,
    atk: 2,
    hp: 4,
    af: 1,
    energy: 5,
    weight: 4,
    name: '心灵巫师',
    effect: 'onClick',
    effect_des: '随机对方一个单位转化为我方随机单位',
    effectFunc: 'magicWizard',
    img: 'magic_unit_11',
  },
  {
    raceId: 2,
    unit_id: 12,
    atk: 1,
    hp: 1,
    af: 1,
    energy: 1,
    weight: 0,
    name: '青蛙',
    effect: 'onShow',
    effect_des: '我是一只青蛙',
    effectFunc: false,
    img: 'magic_unit_12',
  },
]