export const BUILDING_LIST = [
  {
    raceId: 1,
    building_id: 1,
    energy: 1,
    openUnitIds: [1, 2],
    openBuildingIds: [2],
    name: '孵化场',
    weight: 1,
    img: 'dragon_building_1',
  },
  {
    raceId: 1,
    building_id: 2,
    energy: 2,
    openUnitIds: [3],
    openBuildingIds: [3, 6],
    name: '生命之泉',
    weight: 1,
    img: 'dragon_building_2',
  },
  {
    raceId: 1,
    building_id: 3,
    energy: 2,
    openUnitIds: [4],
    openBuildingIds: [4],
    name: '凋零树',
    weight: 2,
    img: 'dragon_building_3',
  },
  {
    raceId: 1,
    building_id: 4,
    energy: 3,
    openUnitIds: [5],
    openBuildingIds: [5],
    name: '死亡戈壁',
    weight: 3,
    img: 'dragon_building_4',
  },
  {
    raceId: 1,
    building_id: 5,
    energy: 4,
    openUnitIds: [6, 7],
    openBuildingIds: [],
    name: '火焰山',
    weight: 4,
    img: 'dragon_building_5',
  },
  {
    raceId: 1,
    building_id: 6,
    energy: 3,
    openUnitIds: [8, 9],
    openBuildingIds: [7],
    name: '神秘森林',
    weight: 3,
    img: 'dragon_building_6',
  },
  {
    raceId: 1,
    building_id: 7,
    energy: 5,
    openUnitIds: [11],
    openBuildingIds: [8, 11],
    name: '悬浮岛',
    weight: 3,
    img: 'dragon_building_7',
  },
  {
    raceId: 1,
    building_id: 8,
    energy: 5,
    openUnitIds: [12],
    openBuildingIds: [9, 10],
    name: '窥视之眼',
    weight: 4,
    img: 'dragon_building_8',
  },
  {
    raceId: 1,
    building_id: 9,
    energy: 5,
    openUnitIds: [13],
    openBuildingIds: [],
    name: '龙宫',
    weight: 5,
    img: 'dragon_building_9',
  },
  {
    raceId: 1,
    building_id: 10,
    energy: 5,
    openUnitIds: [14],
    openBuildingIds: [],
    name: '龙塔',
    weight: 5,
    img: 'dragon_building_10',
  },
  {
    raceId: 1,
    building_id: 11,
    energy: 4,
    openUnitIds: [10],
    openBuildingIds: [],
    name: '圣殿',
    weight: 3,
    img: 'dragon_building_11',
  },
]